/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.11/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    `maven-publish` // https://docs.gradle.org/current/userguide/publishing_maven.html
    signing
    id("com.diffplug.spotless") version "7.0.0.BETA4"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    testImplementation(libs.logback.classic)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

java {
    withJavadocJar()
    withSourcesJar()
}

publishing { //https://docs.gradle.org/current/userguide/publishing_maven.html
    publications {
        create<MavenPublication>("mavenJava") { //name of the publication
            from(components["java"])
            pom {
                name.set("debugjsse")
                description.set("Debug JSSE Provider")
                url.set("https://github.com/tersesystems/debugjsse")
                licenses {
                    license {
                        name.set("Apache2")
                        url.set("https://github.com/tersesystems/debugjsse/blob/main/LICENSE")
                    }
                }
                developers {
                    developer {
                        id.set("wsargent")
                        name.set("Will Sargent")
                        email.set("will@tersesystems.com")
                    }
                }
                scm {
                    connection.set("scm:git:https://github.com/tersesystems/debugjsse.git")
                    developerConnection.set("scm:git:https://github.com/tersesystems/debugjsse.git")
                    url.set("https://github.com/tersesystems/debugjsse.git")
                }
            }
        }
    }
}

extra["isReleaseVersion"] = !version.toString().endsWith("SNAPSHOT")

signing { // https://docs.gradle.org/current/userguide/signing_plugin.html
    setRequired({
        (project.extra["isReleaseVersion"] as Boolean) // && gradle.taskGraph.hasTask("publishToSonatype")
    })
    useGpgCmd()
    sign(publishing.publications["mavenJava"])
}